services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      # Uncomment these lines when you want to enable remote caching
      # args:
      #   TURBO_TEAM: ${TURBO_TEAM}
      #   TURBO_TOKEN: ${TURBO_TOKEN}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - ./apps/api/.env.docker
    depends_on:
      - database
      - cache
    networks:
      - mtt-network

  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mtt_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mtt-network

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mtt-network

volumes:
  postgres_data:
  redis_data:

networks:
  mtt-network:
    driver: bridge
